# Aplicação
spring.application.name=satguard-api
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:satguarddb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Console H2 (para visualizar o banco no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logs
spring.jpa.show-sql=true